################################
# Site Settings
################################
lang        : "en"
logo        :
title       : "desired persona"
description : "Build a BRAND fueled by Passive Income. Generate Sales from Paid Advertising, Media Buying and Search Engine Optimisation."
author      : "desired persona"
email       : "hello@desiredpersona.com"
newsletter  : "http://eepurl.com/cKS1on"
baseurl     : "" # the subpath of your site, e.g. /blog
url         : "https://desiredpersona.com"
date_format : "%-d %B %Y"
port        : 4000


################################
# Theme Settings
################################
theme       : ark-jekyll-theme
permalink   : /:title/

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: desiredpersona

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages
  - _redirects

exclude:
  - Gemfile.lock
  - node_modules
  


################################
# Analytics Settings
################################
google_analytics: UA-34087082-1
facebook_pixel_id: 1744117355874022


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag

disable_title_output: true # Removes "| site title" from page <title> tag.

social:
  name: desired persona
  links:
    - https://twitter.com/desiredpersona
    - https://plus.google.com/+DesiredPersona
    - https://www.facebook.com/desiredpersona

twitter:
  username: desiredpersona

webmaster_verifications:
  google:
  bing: 27CB7CECB1A5500583738C1DC29E5825
  alexa:
  yandex:

# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)